/*
 * This file has been generated by flow2code
 * See: https://flow.liwe.org
 */

import { ILRequest, ILResponse, ILError, ILiWE } from '../../liwe/types';
import { send_error, send_ok, typed_dict } from "../../liwe/utils";
import { locale_load } from '../../liwe/locale';

import { perms } from '../../liwe/auth';
import { LiWEResponse, sendParametersError, sendResponse } from '../../liwe/response';

import {
	// endpoints function
	delete_system_admin_domain_del, get_system_admin_domains_list, get_system_admin_permissions_list, get_system_domain_create_invite, get_system_domain_current,
	get_system_domain_subdomain_list_managed, get_system_domains_list, get_system_theme_get, get_system_uptime, patch_system_admin_domain_update,
	patch_system_admin_reset_id, patch_system_admin_theme_set, patch_system_domain_update_tiers, post_system_admin_domain_add,
	post_system_admin_domain_create_root, post_system_domain_set, post_system_domain_subdomain_create, post_system_domain_user_assign_role,
	post_system_email_test,
	// functions
	system_db_init, system_domain_get_by_code, system_domain_get_by_id, system_domain_get_by_session, system_domain_get_default,
	system_permissions_register,
} from './methods';

import {
	SystemDomain, SystemDomainAdmin, SystemDomainAdminKeys, SystemDomainKeys, SystemDomainPublic,
	SystemDomainPublicKeys, SystemTheme, SystemThemeKeys,
} from './types';

/*=== f2c_start __header ===*/

/*=== f2c_end __header ===*/

export const init = ( liwe: ILiWE ) => {
	const app = liwe.app;

	console.log( "    - system " );

	liwe.cfg.app.languages.map( ( l ) => locale_load( "system", l ) );
	system_db_init ( liwe );

	app.get ( '/api/system/domains/list', perms( [ "system.domain" ] ),  async ( req: ILRequest, res: ILResponse ) => {
		

		const response = await get_system_domains_list ( req, );
		sendResponse ( res, response );
	} );

	app.post ( '/api/system/domain/set', perms( [ "is-logged" ] ),  async ( req: ILRequest, res: ILResponse ) => {
		const { code, ___errors } = typed_dict( req.body, [
			{ name: "code", type: "string", required: true }
		] );

		if ( ___errors.length ) return sendParametersError ( res, ___errors );

		const response = await post_system_domain_set ( req, code);
		sendResponse ( res, response );
	} );

	app.post ( '/api/system/admin/domain/add', perms( [ "system.domain" ] ),  async ( req: ILRequest, res: ILResponse ) => {
		const { code, name, visible, ___errors } = typed_dict( req.body, [
			{ name: "code", type: "string", required: true },
			{ name: "name", type: "string", required: true },
			{ name: "visible", type: "boolean" }
		] );

		if ( ___errors.length ) return sendParametersError ( res, ___errors );

		const response = await post_system_admin_domain_add ( req, code, name, visible);
		sendResponse ( res, response );
	} );

	app.patch ( '/api/system/admin/domain/update', perms( [ "system.domain" ] ),  async ( req: ILRequest, res: ILResponse ) => {
		const { id, code, name, visible, ___errors } = typed_dict( req.body, [
			{ name: "id", type: "string", required: true },
			{ name: "code", type: "string" },
			{ name: "name", type: "string" },
			{ name: "visible", type: "boolean" }
		] );

		if ( ___errors.length ) return sendParametersError ( res, ___errors );

		const response = await patch_system_admin_domain_update ( req, id, code, name, visible);
		sendResponse ( res, response );
	} );

	app.delete ( '/api/system/admin/domain/del', perms( [ "system.domain" ] ),  async ( req: ILRequest, res: ILResponse ) => {
		const { id, code, ___errors } = typed_dict( req.body, [
			{ name: "id", type: "string" },
			{ name: "code", type: "string" }
		] );

		if ( ___errors.length ) return sendParametersError ( res, ___errors );

		const response = await delete_system_admin_domain_del ( req, id, code);
		sendResponse ( res, response );
	} );

	app.get ( '/api/system/admin/domains/list', perms( [ "system.domain" ] ),  async ( req: ILRequest, res: ILResponse ) => {


		const response = await get_system_admin_domains_list ( req, );
		sendResponse ( res, response );
	} );

	app.post ( '/api/system/admin/domain/create_root', perms( [ "system.admin" ] ),  async ( req: ILRequest, res: ILResponse ) => {
		const { name, total_max_tiers, ___errors } = typed_dict( req.body, [
			{ name: "name", type: "string", required: true },
			{ name: "total_max_tiers", type: "number", required: true }
		] );

		if ( ___errors.length ) return sendParametersError ( res, ___errors );

		const response = await post_system_admin_domain_create_root ( req, name, total_max_tiers);
		sendResponse ( res, response );
	} );

	app.post ( '/api/system/domain/subdomain/create', perms( [ "system.multi-tier.create_sub" ] ),  async ( req: ILRequest, res: ILResponse ) => {
		const { name, tiers_allocated, ___errors } = typed_dict( req.body, [
			{ name: "name", type: "string", required: true },
			{ name: "tiers_allocated", type: "number", required: true }
		] );

		if ( ___errors.length ) return sendParametersError ( res, ___errors );

		const response = await post_system_domain_subdomain_create ( req, name, tiers_allocated);
		sendResponse ( res, response );
	} );

	app.get ( '/api/system/domain/subdomain/list_managed', perms( [ "system.multi-tier.create_sub" ] ),  async ( req: ILRequest, res: ILResponse ) => {
		const { deep, ___errors } = typed_dict( req.query as any, [
			{ name: "deep", type: "boolean" }
		] );

		if ( ___errors.length ) return sendParametersError ( res, ___errors );

		const response = await get_system_domain_subdomain_list_managed ( req, deep);
		sendResponse ( res, response );
	} );

	app.post ( '/api/system/domain/user/assign_role', perms( [ "system.multi-tier.create_sub" ] ),  async ( req: ILRequest, res: ILResponse ) => {
		const { id_user, role, ___errors } = typed_dict( req.body, [
			{ name: "id_user", type: "string", required: true },
			{ name: "role", type: "string", required: true }
		] );

		if ( ___errors.length ) return sendParametersError ( res, ___errors );

		const response = await post_system_domain_user_assign_role ( req, id_user, role);
		sendResponse ( res, response );
	} );

	app.patch ( '/api/system/domain/update_tiers', perms( [ "is-logged" ] ),  async ( req: ILRequest, res: ILResponse ) => {
		const { id_domain, total_max_tiers, ___errors } = typed_dict( req.body, [
			{ name: "id_domain", type: "string", required: true },
			{ name: "total_max_tiers", type: "number", required: true }
		] );

		if ( ___errors.length ) return sendParametersError ( res, ___errors );

		const response = await patch_system_domain_update_tiers ( req, id_domain, total_max_tiers);
		sendResponse ( res, response );
	} );

	app.patch ( '/api/system/admin/theme/set', perms( [ "system.theme" ] ),  async ( req: ILRequest, res: ILResponse ) =>{
		const { changes, ___errors } = typed_dict( req.body, [
			{ name: "changes", type: "any" }
		] );

		if ( ___errors.length ) return sendParametersError ( res, ___errors );

		const response = await patch_system_admin_theme_set ( req, changes);
		sendResponse ( res, response );
	} );

	app.get ( '/api/system/theme/get', perms( [ "is-logged" ] ),  async ( req: ILRequest, res: ILResponse ) => {
		

		const response = await get_system_theme_get ( req, );
		sendResponse ( res, response );
	} );

	app.patch ( '/api/system/admin/reset/id', perms( [ "system.admin" ] ),  async ( req: ILRequest, res: ILResponse ) => {
		const { id, new_id, collection, ___errors } = typed_dict( req.body, [
			{ name: "id", type: "string", required: true },
			{ name: "new_id", type: "string", required: true },
			{ name: "collection", type: "string", required: true }
		] );

		if ( ___errors.length ) return sendParametersError ( res, ___errors );

		const response = await patch_system_admin_reset_id ( req, id, new_id, collection);
		sendResponse ( res, response );
	} );

	app.post ( '/api/system/email/test', perms( [ "is-logged" ] ),  async ( req: ILRequest, res: ILResponse ) => {
		const { email, ___errors } = typed_dict( req.body, [
			{ name: "email", type: "string", required: true }
		] );

		if ( ___errors.length ) return sendParametersError ( res, ___errors );

		const response = await post_system_email_test ( req, email);
		sendResponse ( res, response );
	} );

	app.get ( '/api/system/admin/permissions/list', perms( [ "is-logged" ] ),  async ( req: ILRequest, res: ILResponse ) => {
		

		const response = await get_system_admin_permissions_list ( req, );
		sendResponse ( res, response );
	} );

	app.get ( '/api/system/domain/current',  async ( req: ILRequest, res: ILResponse ) => {
		

		const response = await get_system_domain_current ( req, );
		sendResponse ( res, response );
	} );

	app.get ( '/api/system/domain/create/invite', perms( [ "is-logged" ] ),  async ( req: ILRequest, res: ILResponse ) => {
		const { id_domain, expire, ___errors } = typed_dict( req.query as any, [
			{ name: "id_domain", type: "string", required: true },
			{ name: "expire", type: "number" }
		] );

		if ( ___errors.length ) return sendParametersError ( res, ___errors );

		const response = await get_system_domain_create_invite ( req, id_domain, expire);
		sendResponse ( res, response );
	} );

	app.get ( '/api/system/uptime',  async ( req: ILRequest, res: ILResponse ) => {
		

		const response = await get_system_uptime ( req, );
		sendResponse ( res, response );
	} );

};
