/*
 * This file has been generated by flow2code
 * See: https://flow.liwe.org
 */

import { ILRequest, ILResponse, LCback, ILiweConfig, ILError, ILiWE } from '../../liwe/types';
import { LiWEError, LiWEResponse, responseError, responseSuccess } from '../../liwe/response';
import { $l } from '../../liwe/locale';


import {
	SystemDomain, SystemDomainAdmin, SystemDomainAdminKeys, SystemDomainKeys, SystemDomainPublic,
	SystemDomainPublicKeys, SystemTheme, SystemThemeKeys,
} from './types';

import _module_perms from './perms';

let _liwe: ILiWE = null;

const _ = ( txt: string, vals: any = null, plural = false ) => {
	return $l( txt, vals, plural, "system" );
};

const COLL_SYSTEM_DOMAINS = "system_domains";
const COLL_SYSTEM_THEMES = "system_themes";

/*=== f2c_start __file_header === */
import { keys_filter, merge, set_attr, mkid, challenge_create, sha512 } from '../../liwe/utils';
import { session_get, session_set_val } from '../session/methods';
import { Session } from '../session/types';
import { adb_record_add, adb_query_all, adb_query_one, adb_prepare_filters, adb_find_all, adb_find_one, adb_collection_init, adb_del_one } from '../../liwe/db/arango';
import { send_mail } from '../../liwe/mail';
import { perm_available } from '../../liwe/auth';
import { User } from '../user/types';
import { user_get } from '../user/methods';
import { generate_domain_segment_code, validate_tier_allocation, get_parent_domain_code } from './utils';
import { USER_EVENT_PRE_DELETE } from '../user/events';
import { liwe_event_emit } from '../../liwe/events';

type Permission = {
	name: string,
	description: string,
};

const permissions: Record<string, Permission> = {
};

export const domain_get = async ( id: string = null, code: string = null ) => {
	const [ filters, values ] = adb_prepare_filters( 'sd', { id, code } );
	return await adb_query_one( _liwe.db, `FOR sd IN system_domains ${ filters } RETURN sd`, values );
};

const theme_get = async ( req: ILRequest, clean: boolean = false ) => {
	const domain: SystemDomain = await system_domain_get_by_session( req );
	let theme: SystemTheme = await adb_find_one( req.db, COLL_SYSTEM_THEMES, { domain: domain.code } );

	if ( !theme ) theme = { id: mkid( 'theme' ), domain: domain.code, data: {} };

	if ( clean ) keys_filter( theme, SystemThemeKeys );

	return theme;
};
/*=== f2c_end __file_header ===*/

// {{{ get_system_domains_list ( req: ILRequest, cback: LCBack = null ): Promise<SystemDomain[]>
/**
 *
 * List all visible domains
 *
 *
 * @return domains: SystemDomain
 *
 */
export const get_system_domains_list = async ( req: ILRequest, ): Promise<LiWEResponse<SystemDomain[]>> => {
	/*=== f2c_start get_system_domains_list ===*/
	const sds: SystemDomain[] = await adb_query_all( req.db, `FOR sd IN system_domains FILTER sd.visible == true SORT sd.name RETURN sd` );

	if ( !sds || !sds.length )
		return responseSuccess( sds );

	sds.forEach( ( sd ) => keys_filter( sd, SystemDomainKeys ) );

	return responseSuccess( sds );
	/*=== f2c_end get_system_domains_list ===*/
};
// }}}

// {{{ post_system_domain_set ( req: ILRequest, code: stringcback: LCBack = null ): Promise<SystemDomain>
/**
 *
 * Set the current domain for the user
 *
 * @param code - the domain unique code [req]
 *
 * @return domain: SystemDomain
 *
 */
export const post_system_domain_set = async ( req: ILRequest, code: string ): Promise<LiWEResponse<SystemDomain>> => {
	/*=== f2c_start post_system_domain_set ===*/
	const sd: SystemDomain = await domain_get( null, code );
	const err = { message: 'Domain not found' };
	if ( !sd ) return responseError( err.message );

	await session_set_val( req, 'id_domain', sd.id );
	await session_set_val( req, 'domain_code', sd.code );

	return responseSuccess( null );
	/*=== f2c_end post_system_domain_set ===*/
};
// }}}

// {{{ post_system_admin_domain_add ( req: ILRequest, code: string, name: string, visible?: booleancback: LCBack = null ): Promise<SystemDomain>
/**
 *
 * Adds a new domain to the System.
 *
 * @param code - the domain unique code [req]
 * @param name - the domain name [req]
 * @param visible - if the domain is visible or not [default: true] [opt]
 *
 * @return domain: SystemDomain
 *
 */
export const post_system_admin_domain_add = async ( req: ILRequest, code: string, name: string, visible?: boolean ): Promise<LiWEResponse<SystemDomain>> => {
	/*=== f2c_start post_system_admin_domain_add ===*/
	const dom: SystemDomain = { code: code.toLowerCase(), name, visible, id: mkid( "system" ) };
	const sd: SystemDomain = await system_domain_get_by_code( code );
	const err = { message: 'Domain already exists' };

	if ( sd ) return responseError( err.message );

	await adb_record_add( req.db, COLL_SYSTEM_DOMAINS, dom );

	return responseSuccess( dom );
	/*=== f2c_end post_system_admin_domain_add ===*/
};
// }}}

// {{{ patch_system_admin_domain_update ( req: ILRequest, id: string, code?: string, name?: string, visible?: booleancback: LCBack = null ): Promise<SystemDomain>
/**
 *
 * Updates a domain in the system. The `id` field must be provided.
 *
 * @param id - the domain id [req]
 * @param code - the domain unique code [opt]
 * @param name - the domain name [opt]
 * @param visible - if the domain is visible or not [opt]
 *
 * @return domain: SystemDomain
 *
 */
export const patch_system_admin_domain_update = async ( req: ILRequest, id: string, code?: string, name?: string, visible?: boolean ): Promise<LiWEResponse<SystemDomain>> => {
	/*=== f2c_start patch_system_admin_domain_update ===*/
	let dom: SystemDomain = await system_domain_get_by_id( id );
	const err = { message: 'Domain code already in use by another domain' };

	if ( dom.code != code ) {
		const sd = await system_domain_get_by_code( code );
		if ( sd ) return responseError( err.message );
	}

	set_attr( dom, 'code', code );
	set_attr( dom, 'name', name );
	set_attr( dom, 'visible', visible );

	dom = await adb_record_add( req.db, COLL_SYSTEM_DOMAINS, dom );

	return responseSuccess( dom );
	/*=== f2c_end patch_system_admin_domain_update ===*/
};
// }}}

// {{{ delete_system_admin_domain_del ( req: ILRequest, id?: string, code?: stringcback: LCBack = null ): Promise<string>
/**
 *
 * Delete a domain from the system. You can specify both `id` and `code` for deletion
 *
 * @param id - the domain id [opt]
 * @param code - the domain unique code [opt]
 *
 * @return id_domain: string
 *
 */
export const delete_system_admin_domain_del = async ( req: ILRequest, id?: string, code?: string ): Promise<LiWEResponse<string>> => {
	/*=== f2c_start delete_system_admin_domain_del ===*/
	const sd: SystemDomain = await domain_get( id, code );
	const err = { message: "Domain not found" };

	if ( !sd ) return responseError( err.message );

	// Find all child domains (domains that start with this domain's code + ":")
	const child_domains: SystemDomain[] = await adb_query_all(
		req.db,
		`FOR d IN system_domains
		FILTER STARTS_WITH(d.code, CONCAT(@domain_code, ":"))
		RETURN d`,
		{ domain_code: sd.code }
	);

	// Collect all domain codes to delete (including the main domain)
	const domains_to_delete = [ sd, ...child_domains ];
	const domain_codes = domains_to_delete.map( d => d.code );

	// Find and delete all users in these domains
	const users: User[] = await adb_query_all(
		req.db,
		`FOR u IN users
		FILTER u.domain IN @domain_codes
		RETURN u`,
		{ domain_codes }
	);

	// Trigger USER_EVENT_PRE_DELETE for each user
	for ( const user of users ) await liwe_event_emit( req, USER_EVENT_PRE_DELETE, user );

	// Delete all child domains
	for ( const child_domain of child_domains ) await adb_del_one( req.db, COLL_SYSTEM_DOMAINS, child_domain.id );

	// Update parent's tiers_allocated if this is not a root domain
	const parent_code = get_parent_domain_code( sd.code );
	if ( parent_code ) {
		const parent_domain: SystemDomain = await system_domain_get_by_code( parent_code );
		if ( parent_domain && sd.total_max_tiers ) {
			parent_domain.tiers_allocated = ( parent_domain.tiers_allocated || 0 ) - sd.total_max_tiers;
			await adb_record_add( req.db, COLL_SYSTEM_DOMAINS, parent_domain );
		}
	}

	// Finally, delete the main domain
	await adb_del_one( req.db, COLL_SYSTEM_DOMAINS, sd.id );

	return responseSuccess( sd.id );
	/*=== f2c_end delete_system_admin_domain_del ===*/
};
// }}}

// {{{ get_system_admin_domains_list ( req: ILRequest, cback: LCBack = null ): Promise<SystemDomainAdmin[]>
/**
 *
 * List all domains
 *
 *
 * @return domains: SystemDomainAdmin
 *
 */
export const get_system_admin_domains_list = async ( req: ILRequest, ): Promise<LiWEResponse<SystemDomainAdmin[]>> => {
	/*=== f2c_start get_system_admin_domains_list ===*/
	const sds: SystemDomainAdmin[] = await adb_find_all( req.db, COLL_SYSTEM_DOMAINS, {}, SystemDomainAdminKeys, { sort: [ { field: 'name' } ] } );

	return responseSuccess( sds );
	/*=== f2c_end get_system_admin_domains_list ===*/
};
// }}}

// {{{ post_system_admin_domain_create_root ( req: ILRequest, name: string, total_max_tiers: number ): Promise<SystemDomain>
/**
 * Creates a new root domain with tier allocation capability.
 * Only users with system.admin permission can create root domains.
 *
 * @param name - the domain name [req]
 * @param total_max_tiers - the maximum number of tiers that can be allocated to direct children [req]
 *
 * @return domain: SystemDomain
 */
export const post_system_admin_domain_create_root = async ( req: ILRequest, name: string, total_max_tiers: number ): Promise<LiWEResponse<SystemDomain>> => {
	/*=== f2c_start post_system_admin_domain_create_root ===*/
	// Generate unique domain code
	const code = generate_domain_segment_code();

	// Check if domain code already exists (extremely unlikely but good to verify)
	const existing_domain: SystemDomain = await system_domain_get_by_code( code );
	if ( existing_domain ) {
		return responseError( 'Domain code already exists, please try again' );
	}

	// Create the root domain
	const domain: SystemDomain = {
		id: mkid( "dom" ),
		code: code,
		name,
		visible: true,
		total_max_tiers,
		tiers_allocated: 0,
		id_created_by: req.user.id
	};

	await adb_record_add( req.db, COLL_SYSTEM_DOMAINS, domain );

	return responseSuccess( domain );
	/*=== f2c_end post_system_admin_domain_create_root ===*/
};
// }}}

// {{{ post_system_domain_subdomain_create ( req: ILRequest, name: string, tiers_allocated: number ): Promise<SystemDomain>
/**
 * Creates a subdomain and auto-provisions an admin user for it.
 * Requires system.multi-tier.create_sub permission.
 *
 * @param name - the subdomain name [req]
 * @param tiers_allocated - the number of tiers to allocate to this subdomain [req]
 *
 * @return domain: SystemDomain
 */
export const post_system_domain_subdomain_create = async ( req: ILRequest, name: string, tiers_allocated: number ): Promise<LiWEResponse<SystemDomain>> => {
	/*=== f2c_start post_system_domain_subdomain_create ===*/
	// Get parent domain (user's current domain)
	const parent_domain: SystemDomain = await system_domain_get_by_session( req );

	if ( !parent_domain ) {
		return responseError( 'Parent domain not found or is invalid' );
	}

	// Validate tier allocation
	const validation = validate_tier_allocation( parent_domain, tiers_allocated );
	if ( !validation.success ) {
		return responseError( validation.error );
	}

	// Generate unique code segment and form new domain code
	const code_segment = generate_domain_segment_code();
	const new_domain_code = `${ parent_domain.code }:${ code_segment }`;

	// Create the subdomain
	const domain: SystemDomain = {
		id: mkid( "dom" ),
		code: new_domain_code,
		name,
		visible: true,
		total_max_tiers: tiers_allocated,
		tiers_allocated: 0,
		id_created_by: req.user.id
	};

	await adb_record_add( req.db, COLL_SYSTEM_DOMAINS, domain );

	// Update parent's tiers_allocated
	parent_domain.tiers_allocated = ( parent_domain.tiers_allocated || 0 ) + tiers_allocated;
	await adb_record_add( req.db, COLL_SYSTEM_DOMAINS, parent_domain );

	// Auto-provision admin user for the new subdomain
	const admin_username = `${ new_domain_code }-admin`;
	const admin_email = `${ new_domain_code }-admin@example.com`;
	const admin_password = sha512( mkid( 'pwd' ) );

	const admin_user: User = {
		id: mkid( 'user' ),
		domain: new_domain_code,
		username: admin_username,
		email: admin_email,
		password: admin_password,
		enabled: true,
		language: req.user.language || 'en',
		perms: [ "system.multi-tier.create_sub" ]
	};

	await adb_record_add( req.db, COLL_USERS, admin_user );

	return responseSuccess( domain );
	/*=== f2c_end post_system_domain_subdomain_create ===*/
};
// }}}

// {{{ get_system_domain_subdomain_list_managed ( req: ILRequest, deep?: boolean ): Promise<SystemDomain[]>
/**
 * Lists all domains managed by the current user (own domain + subdomains).
 * Requires system.multi-tier.create_sub permission.
 *
 * @param deep - if true, returns all nested subdomains; if false, only direct children [default: true] [opt]
 *
 * @return domains: SystemDomain
 */
export const get_system_domain_subdomain_list_managed = async ( req: ILRequest, deep: boolean = true ): Promise<LiWEResponse<SystemDomain[]>> => {
	/*=== f2c_start get_system_domain_subdomain_list_managed ===*/
	const user_domain_code = req.user.domain;

	let domains: SystemDomain[] = [];

	if ( deep ) {
		// Return own domain + all nested subdomains
		domains = await adb_query_all(
			req.db,
			`FOR sd IN system_domains
			FILTER sd.code == @domain_code OR STARTS_WITH(sd.code, CONCAT(@domain_code, ":"))
			SORT sd.code
			RETURN sd`,
			{ domain_code: user_domain_code }
		);
	} else {
		// Return own domain + only direct children
		const own_domain = await system_domain_get_by_code( user_domain_code );
		domains.push( own_domain );

		// Get direct children (code matches pattern: user_domain:segment without additional colons)
		const children = await adb_query_all(
			req.db,
			`FOR sd IN system_domains
			FILTER STARTS_WITH(sd.code, CONCAT(@domain_code, ":"))
			AND LENGTH(SPLIT(sd.code, ":")) == @expected_depth
			SORT sd.code
			RETURN sd`,
			{
				domain_code: user_domain_code,
				expected_depth: user_domain_code.split( ":" ).length + 1
			}
		);

		domains = domains.concat( children );
	}

	return responseSuccess( domains );
	/*=== f2c_end get_system_domain_subdomain_list_managed ===*/
};
// }}}

// {{{ post_system_domain_user_assign_role ( req: ILRequest, id_user: string, role: string ): Promise<boolean>
/**
 * Assigns a role (multi-tier or user) to a user within the domain hierarchy.
 * Requires system.multi-tier.create_sub permission.
 *
 * @param id_user - the user ID to assign the role to [req]
 * @param role - the role to assign: 'multi-tier' or 'user' [req]
 *
 * @return success: boolean
 */
export const post_system_domain_user_assign_role = async ( req: ILRequest, id_user: string, role: string ): Promise<LiWEResponse<boolean>> => {
	/*=== f2c_start post_system_domain_user_assign_role ===*/
	// Validate role
	if ( role !== 'multi-tier' && role !== 'user' ) {
		return responseError( 'Invalid role. Must be either "multi-tier" or "user"' );
	}

	// Get target user
	const target_user: User = await user_get( id_user );
	if ( !target_user ) {
		return responseError( 'User not found' );
	}

	// Check if target user is within current user's domain hierarchy
	const current_user_domain = req.user.domain;
	const target_user_domain = target_user.domain;

	if ( target_user_domain !== current_user_domain && !target_user_domain.startsWith( `${ current_user_domain }:` ) ) {
		return responseError( 'Target user is not within your domain hierarchy' );
	}

	// Copy user perms
	let perms = [ ...target_user.perms || [] ];

	// remove the `syste.multi-tier.create_sub` if present
	perms = perms.filter( ( p ) => p != 'system.multi-tier.create_sub' );


	// Update user permissions based on role
	if ( role === 'multi-tier' ) perms.push( 'system.multi_tier.create_sub' );
	target_user.perms = perms;

	await adb_record_add( req.db, COLL_USERS, target_user );

	return responseSuccess( true );
	/*=== f2c_end post_system_domain_user_assign_role ===*/
};
// }}}

// {{{ patch_system_admin_theme_set ( req: ILRequest, changes?: anycback: LCBack = null ): Promise<SystemTheme>
/**
 *
 * Changes something in the system theme.
 *
 * @param changes - the main changes [opt]
 *
 * @return theme: SystemTheme
 *
 */
export const patch_system_admin_theme_set = async ( req: ILRequest, changes?: any ): Promise<LiWEResponse<SystemTheme>> => {
	/*=== f2c_start patch_system_admin_theme_set ===*/
	let theme: SystemTheme = await theme_get( req );
	const data = { ...theme.data };

	merge( data, changes );
	theme = await adb_record_add( req.db, COLL_SYSTEM_THEMES, theme, SystemThemeKeys );
	theme.data = data;

	return responseSuccess( theme );
	/*=== f2c_end patch_system_admin_theme_set ===*/
};
// }}}

// {{{ get_system_theme_get ( req: ILRequest, cback: LCBack = null ): Promise<SystemTheme>
/**
 *
 *
 * @return theme: SystemTheme
 *
 */
export const get_system_theme_get = async ( req: ILRequest, ): Promise<LiWEResponse<SystemTheme>> => {
	/*=== f2c_start get_system_theme_get ===*/
	const theme: SystemTheme = await theme_get( req, true );

	return responseSuccess( theme );
	/*=== f2c_end get_system_theme_get ===*/
};
// }}}

// {{{ patch_system_admin_reset_id ( req: ILRequest, id: string, new_id: string, collection: stringcback: LCBack = null ): Promise<string>
/**
 *
 * Force an id to be changed on the system.
 * You have to specify the current `id`, the new `id` and the `collection` name.
 *
 * @param id - the current id [req]
 * @param new_id - the new id [req]
 * @param collection - the collection name [req]
 *
 * @return id: string
 *
 */
export const patch_system_admin_reset_id = async ( req: ILRequest, id: string, new_id: string, collection: string ): Promise<LiWEResponse<string>> => {
	/*=== f2c_start patch_system_admin_reset_id ===*/
	const query = `FOR d IN ${ collection } FILTER d.id == '${ id }' UPDATE d WITH { id: '${ new_id }' } IN ${ collection }`;

	await req.db.query( query );

	return responseSuccess( new_id );
	/*=== f2c_end patch_system_admin_reset_id ===*/
};
// }}}

// {{{ post_system_email_test ( req: ILRequest, email: stringcback: LCBack = null ): Promise<boolean>
/**
 *
 * This endpoint tests email sending.
 * You can specify the destination email address to send the message to, but the message itself is defined by the app.
 *
 * @param email - Destination email address [req]
 *
 * @return result: boolean
 *
 */
export const post_system_email_test = async ( req: ILRequest, email: string ): Promise<LiWEResponse<boolean>> => {
	/*=== f2c_start post_system_email_test ===*/
	const err = { message: 'Please check smtp.send_for_real in the config file' };
	if ( req.cfg.smtp.send_for_real == false )
		return responseError( err.message );

	try {
		await send_mail(
			"LiWE System Test Email",
			"This is a test email from LiWE",
			"This is a <b>test email</b> from LiWE",
			email,
			req.cfg.smtp.from,
			req.cfg.smtp.from,
			null,
		);

		return responseSuccess( true );
	} catch ( e ) {
		err.message = e.message;
		return responseError( err.message );
	}
	/*=== f2c_end post_system_email_test ===*/
};
// }}}

// {{{ get_system_admin_permissions_list ( req: ILRequest, cback: LCBack = null ): Promise<object>
/**
 *
 * Returns all the permissions available in the System.
 * The list depends also on the user's permissions:
 * - If the user has `system.admin`, the endpoint will return **all permissions** available
 * - if the user doesn't have `system.admin` the endpoint will return **only the permissions the user already has**.
 * Permissions are returned in an object with: `module name` as key and a string list of permissions available for that module.
 *
 *
 * @return permissions: object
 *
 */
export const get_system_admin_permissions_list = async ( req: ILRequest, ): Promise<LiWEResponse<object>> => {
	/*=== f2c_start get_system_admin_permissions_list ===*/

	// if the user has system.admin, return all permissions
	if ( perm_available( req.user, [ 'system.admin' ] ) ) {
		return responseSuccess( permissions );
	}

	// otherwise, return only the permissions the user already has
	const res: Record<string, Record<string, string>> = {};
	const mods = Object.keys( permissions ) as string[] ?? [];

	mods.forEach( ( module: string ) => {
		const perms: Record<string, string> = permissions[ module ];
		const kp = Object.keys( perms ) as string[] ?? [];
		kp.forEach( ( k: string ) => {
			const txt = perms[ k ];
			if ( perm_available( req.user, [ k ] ) ) {
				if ( !res[ module ] ) res[ module ] = {};
				res[ module ][ k ] = txt;
			}
		} );
	} );

	return responseSuccess( res );
	/*=== f2c_end get_system_admin_permissions_list ===*/
};
// }}}

// {{{ get_system_domain_current ( req: ILRequest, cback: LCBack = null ): Promise<SystemDomainPublic>
/**
 *
 *
 * @return domain: SystemDomainPublic
 *
 */
export const get_system_domain_current = async ( req: ILRequest, ): Promise<LiWEResponse<SystemDomainPublic>> => {
	/*=== f2c_start get_system_domain_current ===*/
	let domain: SystemDomain;

	// console.log( "=== CURRENT: ", req.user );

	// if the user is logged, returns the domain from the session
	if ( req.user ) {
		domain = await system_domain_get_by_session( req );
	} else {
		// otherwise, returns the default domain
		domain = await system_domain_get_default();
	}

	keys_filter( domain, SystemDomainPublicKeys );

	return responseSuccess( domain );
	/*=== f2c_end get_system_domain_current ===*/
};
// }}}

// {{{ get_system_domain_create_invite ( req: ILRequest, id_domain: string, expire: number = 0cback: LCBack = null ): Promise<string>
/**
 *
 * This endpoint creates an invitation token for a domain.
 * The invitation can have an `expire` date, so you can create temporary tokens.
 * The `expire` field is expressed in `minutes`. If you specify a value different that `0`, the token will last the `expire` minutes.
 * If the `expire` is set to `0` (default), the token does not expire.
 *
 * @param id_domain - The Domain ID to create the invite for [req]
 * @param expire - The amount of minutes the link is valid [opt]
 *
 * @return token: string
 *
 */
export const get_system_domain_create_invite = async ( req: ILRequest, id_domain: string, expire: number = 0 ): Promise<LiWEResponse<string>> => {
	/*=== f2c_start get_system_domain_create_invite ===*/
	const err = { message: _( 'Domain not found' ) };
	const domain: SystemDomain = await system_domain_get_by_id( id_domain );

	if ( !domain ) return responseError( err.message );

	// create the token
	const token: Record<string, string | number> = {
		id_domain,
		expire: expire.toString(),
		created: Date.now(),
	};

	token[ 'challenge' ] = challenge_create( [ id_domain, expire.toString(), token.created.toString() ], true );

	// convert the token to a base64 string
	const token_str = Buffer.from( JSON.stringify( token ) ).toString( 'base64' );

	return responseSuccess( token_str );
	/*=== f2c_end get_system_domain_create_invite ===*/
};
// }}}

// {{{ get_system_uptime ( req: ILRequest, cback: LCBack = null ): Promise<number>
/**
 *
 * Returns the system uptime (in seconds)
 *
 *
 * @return uptime: number
 *
 */
export const get_system_uptime = async ( req: ILRequest, ): Promise<LiWEResponse<number>> => {
	/*=== f2c_start get_system_uptime ===*/
	const d = new Date().getTime();
	const uptime = Math.floor( ( d - _liwe.startDate ) / 1000 );

	return responseSuccess( uptime );
	/*=== f2c_end get_system_uptime ===*/
};
// }}}

// {{{ system_domain_get_default ( cback: LCBack = null ): Promise<SystemDomain>
/**
 *
 * This function returns a `SystemDomain` structure by its id.
 *
 *
 * @return : SystemDomain
 *
 */
export const system_domain_get_default = async (): Promise<SystemDomain> => {
	/*=== f2c_start system_domain_get_default ===*/
	const sd: SystemDomain = await system_domain_get_by_code( _liwe.cfg.app.domain );

	return sd;
	/*=== f2c_end system_domain_get_default ===*/
};
// }}}

// {{{ system_domain_get_by_id ( id: string, cback: LCBack = null ): Promise<SystemDomain>
/**
 *
 * This function returns a `SystemDomain` structure by its id.
 *
 * @param id - The Domain id [req]
 *
 * @return : SystemDomain
 *
 */
export const system_domain_get_by_id = async ( id: string, ): Promise<SystemDomain> => {
	/*=== f2c_start system_domain_get_by_id ===*/
	const sd: SystemDomain = await domain_get( id );

	return sd;
	/*=== f2c_end system_domain_get_by_id ===*/
};
// }}}

// {{{ system_domain_get_by_code ( code: string, cback: LCBack = null ): Promise<SystemDomain>
/**
 *
 * This function returns a `SystemDomain` structure by its code.
 *
 * @param code - The Domain code [req]
 *
 * @return : SystemDomain
 *
 */
export const system_domain_get_by_code = async ( code: string, ): Promise<SystemDomain> => {
	/*=== f2c_start system_domain_get_by_code ===*/
	let sd: SystemDomain = null;
	if ( !code || code == '__system__' )
		sd = await system_domain_get_default();
	else
		sd = await domain_get( null, code.toLowerCase() );

	return sd;
	/*=== f2c_end system_domain_get_by_code ===*/
};
// }}}

// {{{ system_domain_get_by_session ( req: ILRequest, cback: LCBack = null ): Promise<SystemDomain>
/**
 *
 * This function returns a `SystemDomain` structure by its code.
 *
 * @param req - The current session request [req]
 *
 * @return : SystemDomain
 *
 */
export const system_domain_get_by_session = async ( req: ILRequest, ): Promise<SystemDomain> => {
	/*=== f2c_start system_domain_get_by_session ===*/
	let sd: SystemDomain = null;

	if ( req?.user?.domain ) {
		const res = { code: req.user.domain } as SystemDomain;
		return res;
	}

	/*
	if ( !req.session ) {
		if ( req.user ) {
			const sess: Session = await session_get( req, ( req.user as any ).session_key, true );
			if ( sess.domain )
				sd = await system_domain_get_by_code( sess.domain );
		}
	} else {
		sd = await system_domain_get_by_code( req.session.domain_code );
	}
	*/

	if ( req?.user ) {
		const user: User = await user_get( req.user.id );

		if ( user ) sd = await system_domain_get_by_code( user.domain );

		// console.log( "===== DOMAIN: ", sd );
	}

	if ( !sd ) sd = await system_domain_get_default();

	return sd;
	/*=== f2c_end system_domain_get_by_session ===*/
};
// }}}

// {{{ system_permissions_register ( module: string, perms: any, cback: LCBack = null ): Promise<boolean>
/**
 *
 * This function is called by every module during the initialization phase.
 * The module calls this function to pass its permissions and descriptions to the system.
 * This data is consumed by `/system/admin/permissions/list` endpoint
 *
 * @param module - The module name [req]
 * @param perms - The module permissions [req]
 *
 * @return : boolean
 *
 */
export const system_permissions_register = async ( module: string, perms: any, ): Promise<boolean> => {
	/*=== f2c_start system_permissions_register ===*/
	permissions[ module ] = perms || {};

	return true;
	/*=== f2c_end system_permissions_register ===*/
};
// }}}

// {{{ system_db_init ( liwe: ILiWE, cback: LCBack = null ): Promise<boolean>
/**
 *
 * Initializes the module's database
 *
 * @param liwe - The Liwe object [req]
 *
 * @return : boolean
 *
 */
export const system_db_init = async ( liwe: ILiWE, ): Promise<boolean> => {
	_liwe = liwe;

	system_permissions_register( 'system', _module_perms );

	await adb_collection_init( liwe.db, COLL_SYSTEM_DOMAINS, [
		{ type: "persistent", fields: [ "id" ], unique: true },
		{ type: "persistent", fields: [ "code" ], unique: true },
		{ type: "persistent", fields: [ "visible" ], unique: false },
	], { drop: false } );

	await adb_collection_init( liwe.db, COLL_SYSTEM_THEMES, [
		{ type: "persistent", fields: [ "id" ], unique: true },
		{ type: "persistent", fields: [ "domain" ], unique: true },
	], { drop: false } );

	/*=== f2c_start system_db_init ===*/
	let domain = liwe.cfg?.app?.domain || 'default';

	let sd: SystemDomain = await system_domain_get_by_code( domain );
	if ( !sd ) {
		sd = { id: mkid( "system" ), code: domain, name: "Default domain", visible: true };
		await adb_record_add( liwe.db, COLL_SYSTEM_DOMAINS, sd );
	}
	/*=== f2c_end system_db_init ===*/

	return true;
};
// }}}


