/* Types file generated by flow2code */

/*=== f2c_start __file ===*/

/*=== f2c_end __file ===*/
/** SystemDomain */
export interface SystemDomain {
	/** the main id field */
	id: string;
	/** The domain unique code */
	code: string;
	/** The domain name */
	name: string;
	/** If the domain is visible */
	visible?: boolean;
	/** The maximum number of tiers that can be allocated to direct children */
	total_max_tiers?: number | null;
	/** The sum of total_max_tiers values of all direct children */
	tiers_allocated?: number;
	/** The user ID who created this domain */
	id_created_by?: string;
}

export const SystemDomainKeys = {
	'id': { type: 'string', priv: false },
	'code': { type: 'string', priv: false },
	'name': { type: 'string', priv: false },
	'visible': { type: 'boolean', priv: true },
	'total_max_tiers': { type: 'number', priv: false },
	'tiers_allocated': { type: 'number', priv: false },
	'id_created_by': { type: 'string', priv: false },
};

/** SystemTheme */
export interface SystemTheme {
	/** the main id field */
	id: string;
	/** The domain code */
	domain: string;
	/** The Theme data */
	data?: any;
}

export const SystemThemeKeys = {
	'id': { type: 'string', priv: false },
	'domain': { type: 'string', priv: true },
	'data': { type: 'any', priv: false },
};

/** SystemDomainAdmin */
export interface SystemDomainAdmin {
	/** the main id field */
	id: string;
	/** The domain unique code */
	code: string;
	/** The domain name */
	name: string;
	/** If the domain is visible */
	visible: boolean;
}

export const SystemDomainAdminKeys = {
	'id': { type: 'string', priv: false },
	'code': { type: 'string', priv: false },
	'name': { type: 'string', priv: false },
	'visible': { type: 'boolean', priv: false },
};

/** SystemDomainPublic */
export interface SystemDomainPublic {
	/** the main id field */
	id: string;
	code?: string;
	name?: string;
}

export const SystemDomainPublicKeys = {
	'id': { type: 'string', priv: false },
	'code': { type: 'string', priv: false },
	'name': { type: 'string', priv: false },
};

